<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Loki.YetAnother" Version="4.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SbmFizikusToMqtt.Application\SbmFizikusToMqtt.Application.csproj"/>
        <ProjectReference Include="..\SbmFizikusToMqtt.Domain\SbmFizikusToMqtt.Domain.csproj"/>
        <ProjectReference Include="..\SbmFizikusToMqtt.HomeAssistantAutoDiscovery\SbmFizikusToMqtt.HomeAssistantAutoDiscovery.csproj"/>
        <ProjectReference Include="..\SbmFizikusToMqtt.MqttConnector\SbmFizikusToMqtt.MqttConnector.csproj"/>
        <ProjectReference Include="..\SbmFizikusToMqtt.SbmConnector\SbmFizikusToMqtt.SbmConnector.csproj"/>
    </ItemGroup>

</Project>
